$ANSIBLE_VAULT;1.1;AES256
33326639383738323461353765393535346461666537643062653534643937623631366365323633
3963333031396564623061323530653764343934336435630a656634656634363138646232333538
62383036313438366662383036353137386361363163396164653862353036346634343634613434
3966363235613765640a646231623164333139343930613038633639376639316563666664633064
63613861633562623865303630633865626135643465633562333332333566383830323531376635
35373665326261373862643637663363316233363565303933626231303835346338366639366261
39653037643831353539333834363065613665333132633165303433373730333265323936393631
61643963353637653962643834656566656365316564616339643835323030643738633163653230
61396661396538623635613163623633353938363166646366333966616633653365323865303166
62313034336366343963383864316530643431333239663463303232373933656661643763646265
32313565316362636164613938316639363134366335376661346566346162396165626565373432
39633433396462623930626235353564333862323733393266386261323766306562363964616162
36363965613434623862613234373564613133643632323235346361326239303038